ABBREVIATIONS = {
    'proco': 'Professional Contacts',
	'procon': 'Professional Contacts',
	'jhow': 'Jackson Howard',
	'smc': 'Self-Modifying Code',
	'kit': 'Rielle "Kit" Peddler',
	'abt': 'Accelerated Beta Test',
	'mopus': 'Magnum Opus',
	'mo': 'Magnum Opus',
	'charizard': 'Scheherazade',
	':charizard:': 'Scheherazade',
	'siphon': 'Account Siphon',
	'deja': 'Déjà Vu',
	'deja vu': 'Déjà Vu',
	'gov takeover': 'Government Takeover',
	'gt': 'Government Takeover',
	'baby': 'Symmetrical Visage',
	'pancakes': 'Adjusted Chronotype',
	'dlr': 'Data Leak Reversal',
	'bn': 'Breaking News',
	'rp': 'Replicating Perftion',
	'neh': 'Near-Earth Hub',
	'pe': 'Perfecting Evolution',
	'white tree': 'Replicating Perfection',
	'black tree': 'Perfecting Evolution',
	'ci': 'Cerebral Imaging',
	'ppvp': 'Prepaid VoicePAD',
	'pvpp': 'Prepaid VoicePAD',
	'sfss': 'Shipment from SanSan',
	'rdi': 'R&D Interface',
	'hqi': 'HQ Interface',
	'gfi': 'Global Food Initiative',
	'dbs': 'Daily Business Show',
	'nre': 'Net-Ready Eyes',
	'elp': 'Enhanced Login Protocol',
	'levy': 'Levy AR Lab Access',
	'oai': 'Oversight AI',
	'fao': 'Forged Activation Orders',
	'psf': 'Private Security Force',
	'david': 'd4v1d',
	'ihw': 'I\'ve Had Worse',
	'qt': 'Quality Time',
	'nisei': 'Nisei Mk II',
	'dhpp': 'Director Haas\' Pet Project',
	'tfin': 'The Future Is Now',
	'ash': 'Ash 2X3ZB9CY',
	'cvs': 'Cyberdex Virus Suite',
	'otg': 'Off the Grid',
	'ts': 'Team Sponsorship',
	'glc': 'Green Level Clearance',
	'blc': 'Blue Level Clearance',
	'pp': 'Product Placement',
	'asi': 'All-Seeing I',
	'nas': 'New Angeles Sol',
	'bbg': 'Breaker Bay Grid',
	'drt': 'Dedicated Response Team',
	'sot': 'Same Old Thing',
	'stamherk': 'Stimhack',
	'stam herk': 'Stimhack',
	'tempo': 'Professional Contacts',
	'ff': 'Feedback Filter',
	'fis': 'Fisk Investment Seminar',
	'fisk': 'Laramy Fisk',
	'lf': 'Lucky Find',
	'prof': 'The Professor',
	'tol': 'Trick of Light',
	'manup': 'Mandatory Upgrades',
	'ij': 'Inside Job',
	'andy': 'Andromeda',
	'qpm': 'Quantum Predictive Model',
	'smashy dino': 'Shattered Remains',
	'smashy dinosaur': 'Shattered Remains',
	'mhc': 'Mental Health Clinic',
	'etf': 'Engineering the Future',
	'st': 'Stronger Together',
	'babw': 'Building a Better World',
	'bwbi': 'Because We Built It',
	'mn': 'Making News',
	'ct': 'Chaos Theory',
	'oycr': 'An Offer You Can\'t Refuse',
	'aoycr': 'An Offer You Can\'t Refuse',
	'hok': 'House of Knives',
	'cc': 'Clone Chip',
	'ta': 'Traffic Accident',
	'jesus': 'Jackson Howard',
	'baby bucks': 'Symmetrical Visage',
	'babybucks': 'Symmetrical Visage',
	'mediohxcore': 'Deuces Wild',
	'calimsha': 'Kate "Mac" McCaffrey',
	'spags': 'Troll',
	'bs': 'Blue Sun',
	'larla': 'Levy AR Lab Access',
	'ig': 'Industrial Genomics',
	'clone': 'Clone Chip',
	'josh01': 'Professional Contacts',
	'hiro': 'Chairman Hiro',
	'director': 'Director Haas',
	'haas': 'Director Haas',
	'zeromus': 'Mushin no Shin',
	'tldr': 'TL;DR',
	'sportsball': 'Team Sponsorship',
	'sports ball': 'Team Sponsorship',
	'sports': 'Team Sponsorship',
	'crfluency': 'Blue Sun',
	'dodgepong': 'Broadcast Square',
	'cheese potato': 'Data Leak Reversal',
	'cheese potatos': 'Data Leak Reversal',
	'cheese potatoes': 'Data Leak Reversal',
	'cycy': 'Cyber-Cipher',
	'cy cy': 'Cyber-Cipher',
	'cy-cy': 'Cyber-Cipher',
	'expose': 'Exposé',
	'sneakysly': 'Stimhack',
	'eap': 'Explode-a-palooza',
	'wnp': 'Wireless Net Pavilion',
	'mcg': 'Mumbad City Grid',
	'sscg': 'SanSan City Grid',
	'jes': 'Jesminder Sareen',
	'jess': 'Jesminder Sareen',
	'jessie': 'Jesminder Sareen',
	'palana': 'Pālanā Foods',
	'palana foods': 'Pālanā Foods',
	'plop': 'Political Operative',
	'polop': 'Political Operative',
	'pol op': 'Political Operative',
	'poop': 'Political Operative',
	'mcc': 'Mumbad Construction Co.',
	'coco': 'Mumbad Construction Co.',
	'moh': 'Museum of History',
	'cst': 'Corporate Sales Team',
	'panera': 'Panchatantra',
	'pancetta': 'Panchatantra',
	'hhn': 'Hard-Hitting News',
	'adap': 'Another Day, Another Paycheck',
	'maus': 'Mausolus',
	'eoi': 'Exchange of Information',
	'oota': 'Out of the Ashes',
	'tw': 'The Turning Wheel',
	'dnn': 'Dedicated Neural Net',
	'ftm': 'Fear The Masses',
	'ttw': 'The Turning Wheel',
	'tw': 'The Turning Wheel',
	'tbf': 'The Black File',
	'bf': 'The Black File',
	'ips': 'Improved Protien Source',
	'nmcg': 'Navi Mumbai City Grid',
	'tpof': 'The Price of Freedom',
	'pgo': 'Power Grid Overload',
	'am': 'Archived Memories',
	'ro': 'Reclamation Order',
	'mch': 'Mumbad City Hall',
	'nach': 'New Angeles City Hall',
	'dl': 'Dirty Laundry',
	'tr': 'Test Run',
	'itd': 'IT Department',
	'it': 'IT Department',
	'vi': 'Voter Intimidation',
	'fte': 'Freedom Through Equality',
	'vbg': 'Virus Breeding Ground',
	'exploda': 'Explode-a-palooza',
	'ctm': 'NBN: Controlling the Message',
	'hrf': 'Hyouba Research Facility',
	'abr': 'Always Be Running',
	'dan': 'Deuces Wild',
	':dan:': 'Deuces Wild',
	':themtg:': 'Deuces Wild',
	'pornstache': 'Hernando Cortez',
	'porn stache': 'Hernando Cortez',
	'porn-stache': 'Hernando Cortez',
	'vape': 'Deuces Wild',
	'fair1': 'Fairchild 1.0',
	'fc1': 'Fairchild 1.0',
	'fc 1': 'Fairchild 1.0',
	'fair2': 'Fairchild 2.0',
	'fc2': 'Fairchild 2.0',
	'fc 2': 'Fairchild 2.0',
	'fair3': 'Fairchild 3.0',
	'fc3': 'Fairchild 3.0',
	'fc 3': 'Fairchild 3.0',
	'fc4': 'Fairchild',
	'fc 4': 'Fairchild',
	'fcp': 'Fairchild',
	'fcprime': 'Fairchild',
	"fc'": 'Fairchild',
	'psk': 'Rumor Mill',
	'khantract': 'Temüjin Contract',
	'tc': 'Temüjin Contract',
	'clippy': 'Paperclip',
	'clippit': 'Paperclip',
	'crouton': 'Curtain Wall',
	'bon': 'Weyland: Builder of Nations',
	'aot': 'Archtects of Tomorrow',
	'pu': 'Jinteki: Potential Unleashed',
	'smoke': 'Ele "Smoke" Scovak',
	'bl': 'Biotic Labor',
	'ad': 'Accelerated Diagnostics',
	'sfm': 'Shipment from Mirrormorph',
	'sfmm': 'Shipment from Mirrormorph',
	'sfk': 'Shipment from Kaguya',
	'psyfield': 'Psychic Field',
	'psy field': 'Psychic Field',
	'psifield': 'Psychic Field',
	'psi field': 'Psychic Field',
	'mvt': 'Mumbad Virtual Tour',
	'eff comm': 'Efficiency Committee',
	'eff com': 'Efficiency Committee',
	'effcomm': 'Efficiency Committee',
	'effcom': 'Efficiency Committee',
	'ec': 'Efficiency Committee',
	'd1en': 'Memstrips',
	'dien': 'Memstrips',
	'ber': 'Bioroid Efficiency Research',
	'ci fund': 'C.I. Fund',
	'vlc': 'Violet Level Clearance',
	'pv': 'Project Vitruvius',
	'sac con': 'Sacrificial Construct',
	'saccon': 'Sacrificial Construct',
	'sc': 'Sacrificial Construct',
	'willow': "Will-o'-the-Wisp",
	'will o': "Will-o'-the-Wisp",
	'willo': "Will-o'-the-Wisp",
	'will-o': "Will-o'-the-Wisp",
	'wotw': "Will-o'-the-Wisp",
	'fihp': 'Friends in High Places',
	'otl': 'On the Lam',
	'sifr': 'Ṣifr',
	'piot': 'Peace in Our Time',
	'sna': 'Sensor Net Activation',
	'sunya': 'Sūnya',
	'barney': 'Bryan Stinson',
	'hat': 'Hellion Alpha Test',
	'hbt': 'Hellion Beta Test',
	'csm': 'Clone Suffrage Movement',
	'beth': 'Beth Kilrain-Chang',
	'eli': 'Eli 1.0',
	'eirik': 'Leela Patel: Trained Pragmatist',
	'karl erik': 'Rielle "Kit" Peddler',
	'potato': 'Jinteki: Potential Unleashed',
	'nikolai': 'Jesminder Sareen: Girl Behind The Curtain'
}

SUPERSCRIPTS = {
		'0': '⁰',
		'1': '¹',
		'2': '²',
		'3': '³',
		'4': '⁴',
		'5': '⁵',
		'6': '⁶',
		'7': '⁷',
		'8': '⁸',
		'9': '⁹',
		'X': 'ˣ',
		'x': 'ˣ'
	}
