SAVED = ["Reina Roja: Freedom Fighter",
		"Retrieval Run",
		"Singularity",
		"Spinal Modem",
		"Darwin",
		"Force of Nature",
		"Imp",
		"Hemorrhage",
		"Morning Star",
		"Liberated Account",
		"Scrubber",
		"Xanadu",
		"Emergency Shutdown",
		"Doppelgänger",
		"HQ Interface",
		"Faerie",
		"Peacock",
		"Pheromones",
		"Fall Guy",
		"Mr. Li",
		"Haas-Bioroid: Stronger Together",
		"Project Ares",
		"Project Vitruvius",
		"Hudson 1.0",
		"Green Level Clearance",
		"Ash 2X3ZB9CY",
		"Strongbox",
		"Project Beale",
		"TGTBT",
		"Flare",
		"Pop-up Window",
		"Wraparound",
		"Bernice Mai",
		"Chaos Theory: Wünderkind",
		"Indexing",
		"Notoriety",
		"Test Run",
		"Dinosaurus",
		"All-nighter",
		"Dyson Mem Chip",
		"Underworld Contact",
		"Braintrust",
		"Ronin",
		"Himitsu-Bako",
		"Swordsman",
		"Whirlpool",
		"Yagura",
		"Celebrity Gift",
		"Trick of Light",
		"Hokusai Grid",
		"Project Atlas",
		"The Cleaners",
		"Dedicated Response Team",
		"Elizabeth Mills",
		"GRNDL Refinery",
		"Caduceus",
		"Hive",
		"Punitive Counterstrike",
		"False Lead"]

RIP = ["Noise: Hacker Extraordinaire",
"Déjà Vu",
"Grimoire",
"Corroder",
"Djinn",
"Medium",
"Parasite",
"Wyrm",
"Yog.0",
"Wyldside",
"Account Siphon",
"Desperado",
"Lemuria Codecracker",
"Ninja",
"Data Dealer",
"Decoy",
"Kate \"Mac\" McCaffrey: Digital Tinker",
"The Toolbox",
"Akamatsu Mem Chip",
"Net Shield",
"Zaibatsu Loyalty",
"Cell Portal",
"Chum",
"Data Mine",
"Precognition",
"Akitaro Watanabe",
"Haas-Bioroid: Engineering the Future",
"Accelerated Beta Test",
"Corporate Troubleshooter",
"Experiental Data",
"AstroScript Pilot Program",
"Breaking News",
"Oslo City Grid",
"Matrix Analyzer",
"Posted Bounty",
"Security Subcontract",
"Aggressive Negotiations",
"Scorched Earth",
"Research Station",
"Whizzard: Master Gamer",
"Cortez Chip",
"ZU.13 Key Master",
"The Helpful AI",
"Plascrete Carapace",
"Mandatory Upgrades",
"Janus 1.0",
"Snowflake",
"Restructured Datapool",
"TMI",
"Dracō",
"Vamp",
"Satellite Uplink",
"e3 Feedback Implants",
"Compromised Employee",
"Snowball",
"Encryption Protocol",
"Sherlock 1.0",
"Jinteki: Replicating Perfection",
"Fetal AI",
"Sensei",
"Big Brother",
"ChiLo City Grid",
"Power Grid Overload",
"Amazon Industrial Zone",
"Executive Retreat",
"Freelancer",
"Nerve Agent",
"Joshua B.",
"Muresh Bodysuit",
"Snitch",
"Personal Workshop",
"Public Sympathy",
"Viper",
"Edge of World",
"Sunset",
"Marked Accounts",
"Woodcutter",
"Commercialization",
"Private Contracts",
"Chimera",
"Disrupter",
"Crescentus",
"Deus X",
"Inside Man",
"Hourglass",
"Dedicated Server",
"Bullfrog",
"Uroboros",
"Net Police",
"Weyland Consortium: Because We Built It",
"Government Contracts",
"Tyrant",
"Oversight AI",
"Surge",
"Andromeda: Dispossessed Ristie",
"Networking",
"Quality Time",
"Replicator",
"Creeper",
"Kraken",
"Kati Jones",
"Eve Campaign",
"Rework",
"Data Hound",
"Salvage",
"Simone Diego",
"Foxfire",
"Data Leak Reversal",
"R&D Interface",
"Deep Thought",
"New Angeles City Hall",
"Eli 1.0",
"Ruhr Valley",
"Midori",
"NBN: The World is Yours*",
"Midseason Replacements",
"Burke Bugs",
"Corporate War",
"Frame Job",
"Pawn",
"Rook",
"Hostage",
"Gorman Drip v1",
"Lockpick",
"False Echo",
"Motivation",
"John Masanori",
"NEXT Bronze",
"Character Assassination",
"Jackson Howard",
"Invasion of Privacy",
"Geothermal Fracking",
"Swarm",
"Cyberdex Trial",
"Grim",
"Bishop",
"Scheherazade",
"Hard at Work",
"Recon",
"Copycat",
"Leviathan",
"Eureka!",
"Record Reconstructor",
"Prepaid VoicePAD",
"Wotan",
"Hellion Alpha Test",
"Clone Retirement",
"Shipment from SanSan",
"Muckraker",
"Off the Grid",
"Profiteering",
"Restructure",
"Deep Red",
"Knight",
"Running Interference",
"Expert Schedule Analyzer",
"Grifter",
"Torch",
"Woman in the Red Dress",
"Raymond Flint",
"Isabel McGuire",
"Accelerated Diagnostics",
"Unorthodox Predictions",
"Sundew",
"City Surveillance",
"Snoop",
"Ireress",
"Power Shutdown",
"Paper Wall",
"Interns",
"Keyhole",
"Activist Support",
"Lawyer Up",
"Leverage",
"Garrote",
"LLDS Processor",
"Sharpshooter",
"Capstone",
"Starlight Crusade Funding",
"Rex Campaign",
"Fenris",
"Panic Button",
"Shock!",
"Tsurugi",
"Sweeps Week",
"RSVP",
"Curtain Wall",
"Veterans Program",
"Quest Completed",
"Tallie Perrault",
"Executive Wiretaps",
"Blackguard",
"CyberSolutions Mem Chip",
"Alpha",
"Omega",
"Blackmail",
"Blue Level Clearance",
"Toshiyuki Sakai",
"Restoring Face",
"Market Research",
"GRNDL: Power Unleashed",
"Vulcan Coverup",
"Subliminal Messaging",
"Queen's Gambit",
"Dyson Fractal Generator",
"Silencer",
"Savoir-faire",
"Power Nap",
"Paintbrush",
"Lucky Find",
"Gyri Labyrinth",
"Reclamation Order",
"Broadcast Square",
"Corporate Shuffle",
"Caprice Nisei",
"Shinobi",
"Marker",
"Witness Tampering",
"NAPD Contract",
"Quandary"]
